# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "git@github.com:glitch-soc/mastodon.git";
    rev = "2f6ac6b4327898744289c4d3c35ae44bd9dbcb3f";
    sha256 = "1jd8370d0s42118fhaqn2n666mgycsi9ydrymnc27dykbsh15nkd";
  };
in applyPatches {
  inherit src;
  patches = [];
}
