# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "git@github.com:glitch-soc/mastodon.git";
    rev = "f233b5ed251bd5efd702e664b48054dbbc2ab4c6";
    sha256 = "0kb6b5h33h7kinxkcnzncga3y47yqq5ii27kwwpy9bian5jv1n6v";
  };
in applyPatches {
  inherit src;
  patches = [];
}
