# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/vy-let/mastodon.git";
    rev = "5e6f15064fdb01a2a914a699cbc7dcc4538a9344";
    sha256 = "sha256-36TdnuliTwXF55Dm9jSerpuP4O1dd53qT1dxpxF4xlk=";
  };
in applyPatches {
  inherit src;
  patches = [];
}
